server:
  port: 8082

spring:
  application:
    name: 'fornecedor'
  datasource:
    password: apartamento141
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/fornecedor?useTimezone=true&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/fornecedor?useTimezone=true&serverTimezone=UTC
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

